### ISSUE TITLE
Add builtwith as subdomain source

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/scilla#109]
https://github.com/edoardottt/scilla/issues/51#issuecomment-1759174142

**Comment by ajistrying** [comment]
Hi there, is this project still being actively worked on? If so I'd like to take this issue 👍

**Comment by edoardottt** [comment]
> Hi there, is this project still being actively worked on? If so I'd like to take this issue 👍

for sure, done

**Comment by ajistrying** [comment]
[First attempt](https://github.com/edoardottt/scilla/pull/122) is ready for review @edoardottt

**Comment by edoardottt** [comment]
Completed, thanks @ajistrying !
