### ISSUE TITLE
Subdomain Enumeration Does not Working

### ISSUE THREAD

**Issue by thevillagehacker** [edoardottt/scilla#11]
**Summary**
Scilla having a feature to enumerate the target subdomains. When you give the input target and run it returns a error like below:
```sh
target: google.com
2020/12/22 17:29:57 failed to open /usr/bin/lists/subdomains.txt
```
I am running `scilla` in WSL Ubuntu 20.04

**To Reproduce**
1. git clone the repository
2. go build
3. cp `scilla` build file to `/usr/local/bin`
4. run the following
```sh
scilla subdomain -target google.com
```

**Expected behavior**
It should return Subdomains as output.

**Screenshots**
![image](https://user-images.githubusercontent.com/32858162/102886833-db8c4000-447b-11eb-8418-fa0a7145468d.png)

**Comment by thevillagehacker** [comment]
## Same Results when running from scilla folder
```sh
[naveenj@Saturn|05:36 PM|~/tools/scilla]$ go run scilla.go subdomain -target google.com
go: downloading github.com/asaskevich/govalidator v0.0.0-20200907205600-7a23bdc65eef
go: downloading github.com/fatih/color v1.10.0
go: extracting github.com/fatih/color v1.10.0
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/mattn/go-colorable v0.1.8
go: extracting github.com/asaskevich/govalidator v0.0.0-20200907205600-7a23bdc65eef
go: extracting github.com/mattn/go-colorable v0.1.8
go: extracting github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
go: extracting golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
go: finding github.com/asaskevich/govalidator v0.0.0-20200907205600-7a23bdc65eef
go: finding github.com/fatih/color v1.10.0
go: finding github.com/mattn/go-colorable v0.1.8
go: finding github.com/mattn/go-isatty v0.0.12
go: finding golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
*****************************************
*                 _ _ _                 *
*        ___  ___(_) | | __ _           *
*       / __|/ __| | | |/ _` |          *
*       \__ \ (__| | | | (_| |          *
*       |___/\___|_|_|_|\__,_|          *
*                                       *
* https://github.com/edoardottt/scilla  *
* https://www.edoardoottavianelli.it    *
*                                       *
*****************************************

=============== SUBDOMAINS ===============
target: google.com
2020/12/22 17:36:42 failed to open /usr/bin/lists/subdomains.txt
exit status 1
```

**Comment by edoardottt** [comment]
Yes, you're copying the default lists in the wrong folder. The path should be `/usr/bin` and not `/usr/local/bin`.

Anyway, there is the `Makefile` file, that is the automatic process to do this. Be sure you're in the scilla folder and type `make linux` to install it and `make unlinux` to uninstall.

Let me know if there are other kind of problems, or just close the issue :+1:  :)

**Comment by thevillagehacker** [comment]
@edoardottt ah sorry my bad . Working good now.
Thank you 
Naveen

**Comment by thevillagehacker** [comment]
closed

**Comment by munntjlx** [comment]
Even though this is closed putting things in /usr/bin/lists makes OSX VERY angry. Might it not be advisable to allow for this file to be specificed in other, non protected directories?

**Comment by edoardottt** [comment]
Hi @munntjlx ! thanks for the suggestion. If you want open an issue and we can discuss about that what could be the best option :)
