### ISSUE TITLE
Add dnsrepo.noc.org as subdomain source

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/scilla#110]
https://github.com/edoardottt/scilla/issues/51#issuecomment-1759174142

**Comment by iamshreeram** [comment]
@edoardottt , You can assign this to me. 

Summary of the lua code - 
1. If the client key is provided in context, [URL is built](https://github.com/owasp-amass/amass/blob/5f1f7176bae60975c1e5be64273cb201f1bb37c3/resources/scripts/api/dnsrepo.ads#L63) and the response is a `json` which is parsed 
2. If the auth key is **nil**, app calls the [scrape function](https://github.com/owasp-amass/amass/blob/5f1f7176bae60975c1e5be64273cb201f1bb37c3/resources/scripts/api/dnsrepo.ads#L35C9-L35C76) that extracts the data from webpage (table). 

Quick question - 
1. Do we have have to impl. the scrape function to get the data from the table? or 
2. Should we implement the code to take up the client key?

**Comment by edoardottt** [comment]
It's up to you...
If you want you can implement both (if auth is present use 1 otherwise 2)
But just the scrape function is okay.

In the first case see how the virustotal auth is already implemented

**Comment by iamshreeram** [comment]
@edoardottt , I can pick this up. I'm using goquery to scrape the table data from html page

**Comment by edoardottt** [comment]
Completed, thanks @iamshreeram !
