### ISSUE TITLE
Remove bufferoverrun as subdomain source

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/scilla#112]
https://github.com/edoardottt/scilla/issues/51#issuecomment-1759174142

**Comment by carlosfrodrigues** [comment]
Hello, 
I'm interested in this one. Could you assign this for me?

**Comment by edoardottt** [comment]
For sure @carlosfrodrigues ! It's not needed to delete completely this file https://github.com/edoardottt/scilla/blob/main/pkg/opendb/bufferoverrun.go. It's okay to remove that source in the enumeration phase in other files. 

Let me know if you need some guidance :)

**Comment by carlosfrodrigues** [comment]
Hi @edoardottt , I was looking at the code. Isn't bufferoverrun already commented on the runner.go, so it's already not enable, right?
https://github.com/edoardottt/scilla/blob/59bddf4de57f3e7fc25d421f6dc91d4895a65f26/pkg/runner/runner.go#L186

**Comment by edoardottt** [comment]
Yes, sorry you're right.

If you want you can take https://github.com/edoardottt/scilla/issues/113
