### ISSUE TITLE
Install issue: //go:build comment without // +build comment

### ISSUE THREAD

**Issue by blackcodersec** [edoardottt/scilla#148]
check the error!
![image](https://github.com/user-attachments/assets/408f4d8d-dc52-478a-ae6e-4fde357aeb52)

**Comment by edoardottt** [comment]
which golang version are you using?

**Comment by blackcodersec** [comment]
go version go1.23.1 linux/amd64

**Comment by edoardottt** [comment]
Hi, it seems an issue related to go versions < 1.18.  
I've never encountered such issue. These are the answers I'm finding online:
- https://new.reddit.com/r/golang/comments/rn25ov/encountering_gobuild_comment_without_build/
- https://stackoverflow.com/questions/68360688/whats-the-difference-between-gobuild-and-build-directives

Let me know if that helps, 
edoardo

**Comment by edoardottt** [comment]
@blackcodersec let me know if you've managed to solve the issue. Let's close this, otherwise will be stale

**Comment by blackcodersec** [comment]
Hi there,
I used `snap` cmd, and my issue is resolved now.
