### ISSUE TITLE
Spyse implementation

### ISSUE THREAD

**Issue by Luci-d** [edoardottt/scilla#32]
**Describe the solution you'd like**
We are suggesting you add Spyse as one of the data sources for: DNS, subdomain enumeration, retrieving web information, hosts, certificates, and ports. 
Potential is immense. Contact us if you need any help or a free subscription to make it free for users.

**Describe alternatives you've considered**
Alternatives could be shodan or censys.

**Additional context**
I'm offering Spyse because it has different scanning and analyzing systems that provide a more clear and sometimes larger amounts of data. 

Notice: I work for Spyse.

**Comment by edoardottt** [comment]
Hi @Luci-d ! Really Thank u for this proposal.  
Currently I'm really full of work and I can't think about this :(  
I think in the weekend I will be free to discuss everything!  
I will ping you to request additional informations :+1: 
My email is edoardott@gmail.com, send me an email with yours

**Comment by Luci-d** [comment]
> Hi @Luci-d ! Really Thank u for this proposal.
> Currently I'm really full of work and I can't think about this :(
> I think in the weekend I will be free to discuss everything!
> I will ping you to request additional informations 👍
> My email is [edoardott@gmail.com](mailto:edoardott@gmail.com), send me an email with yours

Sure, totally understand. 
Here are my contacts: 
– mark@spyse.com
– https://twitter.com/_markroze
– https://www.linkedin.com/in/mark-roze/

**Comment by edoardottt** [comment]
Hi @Luci-d , I'm back!

Scilla now provides directories, subdomains, dns and port enumeration.  
I was seeing the Spyse API docs, I don't see any subdomains API endpoints, am I wrong?

For now I'm interested in only subdomains api. Let me know :)

**Comment by scanpatch** [comment]
Hi @edoardottt !

You should take a look at the https://spyse-dev.readme.io/reference/domains#domain_search method. It can be used to search for domains ending with a dot + parent domain name.

Examples and a detailed descriptions can be found here: https://github.com/spyse-com/go-spyse

Also, here is an example of subdomain enumeration using Spyse in the Projectdiscovery Subfinder tool: https://github.com/projectdiscovery/subfinder/blob/82e8b7dc3418cf10948f68200daaed22dc3c8039/v2/pkg/subscraping/sources/spyse/spyse.go#L20

**Comment by edoardottt** [comment]
Thank for your comment! I was having fun refactoring the whole project.

This is the Spyse implementation, since I don't have an API key, do you think it is okay? 

https://github.com/edoardottt/scilla/blob/main/opendb/spyse.go

**Comment by scanpatch** [comment]
@edoardottt I've checked the integration using my API token, and I can confirm that everything works fine. 

But with current implementation users, you cannot get more than 10 000 subdomains from Spyse, because the "Scroll" method isn't supported.

P.S. I can send you an API token for further tests or integrations. Just register on spyse.com and send me your email.

**Comment by edoardottt** [comment]
Thank you @scanpatch for the help and the pull request you made.  
For now I'm ok with this, unfortunately I have so much backlog to solve.  
 If, for whatever reason, I will need a key I will ping you, *thank you another time*!.

edoardottt, (edoardott@gmail.com if you have to text me)
