### ISSUE TITLE
Better protocol handling

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/scilla#36]
When the user inputs a target, for example `https://www.edoardoottavianelli.it`, scilla should remember that the user inputted that protocol, and it doesn't try to use http or another protocol.  
The protocol handling now is way confusionary, as we can see in the [main.go](https://github.com/edoardottt/scilla/blob/main/main.go) file.

**Comment by edoardottt** [comment]
I tag you if you want to work on this @teezzan. I will provide more informations, let me know, I can also do this :)

**Comment by teezzan** [comment]
I will check it out. Thanks

**Comment by teezzan** [comment]
Can you explain a little bit more? I would love to work on it.

**Comment by edoardottt** [comment]
In the main.go file there are the subcommand handlers functions (dns, dir.. etc..), they take the input and then performes the required actions.

Now the handlers take the input and then try to manage with the target (if the protocol exists or not, if not add http://, etc..), but the problem is that the managment is way confusionary.
 
The optimal behaviour is:

- See if the target has the protocol:
        - if the protocol exists, save it and then use that one.
        - if the protocol doesn't exists, use `http://`.
 
- Then there are points in the code where we need to remove the protocol, and it's okay. But then we have to add back the inputted protocol, for example if the user inputs `https://edoardoottavianelli.it` for the report subcommand: 

        - for the subdomain command we remove the protocol and we enumerate subdomains, but then we have to use https and http when we add back the protocol
        - for the directories enumeration we have to use https, not http
  
Let me know if this is clear or not, if not it's okay I can work on this.  
If its clear, don't worry if there could be little issue, I will fix them.

**Comment by edoardottt** [comment]
- [ ] Subdomain Input protocol Handling
- [ ] Directory Input protocol Handling
- [ ] Crawler Input protocol Handling

**Comment by teezzan** [comment]
Awesome Job @edoardottt. I am sorry for not taking it up. School came up.

**Comment by edoardottt** [comment]
> Awesome Job @edoardottt. I am sorry for not taking it up. School came up.

Don't worry about random projects, concentrate and put effort on school. **Learn!**

Have a good day boy
