### ISSUE TITLE
Feauture request

### ISSUE THREAD

**Issue by soupnatzi** [edoardottt/scilla#55]
is there a way to instead of subdomain enumeration example "dev.example.com" what about "example.dev.dev.com"?

**Comment by edoardottt** [comment]
Just to be sure we are aligned.. you should have a target, like `example.com`, in this case your target is `dev.com`?  

Maybe I'm not getting what exactly you would like to do.. can you explain better ?

**Comment by soupnatzi** [comment]
no not at all this is what i mean lets say a companies main domain is dev.com now this company may have jira.dev.com but also it can have dev.atlassian.net the feature request is for scilla to look for dev.atlassian.net.

**Comment by edoardottt** [comment]
Okay, I got what you mean. I think this is not a feature I will add in scilla, I think fits more in [lit-bb-hack-tools](https://github.com/edoardottt/lit-bb-hack-tools). I will work on this in the next days (days....weeks? Idk) :) Thank you for your contribution :)
