### ISSUE TITLE
Writing results of only valid live  subdomains to a txt file 

### ISSUE THREAD

**Issue by excep** [edoardottt/scilla#59]
I don't know if this works or not or it does then writes outputs to somewhere else except the path I give if so then how to do this !!? writing output to a txt file in a specific path !!?

**Comment by edoardottt** [comment]
Added.
See here the [devel branch](https://github.com/edoardottt/scilla/tree/devel).
Compile that version and try it a lil bit. Notify me if you find errors, in few days I will roll out a nrew release :)

See [here](https://github.com/edoardottt/scilla/tree/devel#get-started-) how to use the new options `-oj`, `-oh`, `-ot`.

**Comment by edoardottt** [comment]
pushed everything on main branch

**Comment by edoardottt** [comment]
Added in [v1.2.2](https://github.com/edoardottt/scilla/releases/tag/v1.2.2)
