### ISSUE TITLE
docker build an error occurs

### ISSUE THREAD

**Issue by Trapshell** [edoardottt/scilla#72]
system：kali linux
When I try docker build an error occurs
```sh
git clone https://github.com/edoardottt/scilla.git
cd scilla
docker build -t scilla .
```
##Error message
> [4/5] RUN go install -v ./...:
#6 3.564 go: golang.org/x/net@v0.0.0-20220524220425-1d687d428aca requires
#6 3.564        golang.org/x/sys@v0.0.0-20211216021012-1d35b9e2eb4e: missing go.sum entry; to add it:
#6 3.564        go mod download golang.org/x/sys
------
executor failed running [/bin/sh -c go install -v ./...]: exit code: 1
<img width="941" alt="Snipaste_2022-08-18_15-36-36" src="https://user-images.githubusercontent.com/106905547/185337394-203ceadf-b40b-4a71-b930-4a6f4dc06e38.png">

## about  Building from source
How can I do the upgrade?
Because I don't see any description of "update" :see_no_evil:

**Comment by edoardottt** [comment]
I've updated the Dockerfile
