### ISSUE TITLE
JSON Output

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/scilla#8]
Output as JSON file when output option is selected.

**Comment by teezzan** [comment]
I would love to work on this.

**Comment by teezzan** [comment]
I would love to work on this.

**Comment by teezzan** [comment]
Thanks a lot. I am just learning Go and  haven't used it for a lot of project. I definitely will need your help. Thanks for offering to help.

**Comment by teezzan** [comment]
@edoardottt  How do you propose the `key:value` pair if JSON be constructed from the output of `scilla`. Say for example, I have a text output for a port scanning as shown below.
```
http://oauife.edu.ng:25
http://oauife.edu.ng:22
http://oauife.edu.ng:21
http://oauife.edu.ng:53
http://oauife.edu.ng:80

```
How do you propose I put this into `key:value` form?

And for a `dns` scanning output as shown below.
```
216.58.223.238
2c0f:fb50:4003:802::200e
google.com.
ns1.google.com.
ns2.google.com.
ns3.google.com.
ns4.google.com.
aspmx.l.google.com.
alt1.aspmx.l.google.com.
alt2.aspmx.l.google.com.
alt3.aspmx.l.google.com.
alt4.aspmx.l.google.com.
xmpp-server.l.google.com.
alt4.xmpp-server.l.google.com.
alt1.xmpp-server.l.google.com.
alt3.xmpp-server.l.google.com.
alt2.xmpp-server.l.google.com.
```

Thank you for your help.

**Comment by edoardottt** [comment]
For the ports you can just put them in a list called 'ports'.
Like:
{
    "ports": [
        http://oauife.edu.ng:25,
        http://oauife.edu.ng:22,
        http://oauife.edu.ng:21,
        http://oauife.edu.ng:53,
        http://oauife.edu.ng:80 <http://oauife.edu.ng/>
    ]
}

For the DNS you can differentiate the various records, like the same you do
with ports (an array), but with the keys named as the dns records (A, AAAA,
NS, MX, TXT, SRV...).
For the subdomains and directories you can use the same structure as the
ports.

Let me know if there is something not clear, I'm here to help u :)

edoardottt

Il giorno lun 9 ago 2021 alle ore 17:27 Yusuf Taiwo Hassan <
***@***.***> ha scritto:

**Comment by edoardottt** [comment]
https://github.com/edoardottt/scilla/pull/35
